# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: ipriestley
      PGPASSWORD:
      PGDATABASE: todo_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: localhost
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: ipriestley
      POSTGRES_PASSWORD:
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
      PORT: 4000
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
